import * as THREE from 'three';
import { PostFX } from './render/postfx.js';
import { Environment } from './world/environment.js';
import { CityMap } from './world/citymap.js';
import { CollisionWorld } from './world/collision.js';
import { City } from './world/city.js';

const q = new URLSearchParams(location.search);
const renderer = new THREE.WebGLRenderer({ antialias: false, powerPreference: 'high-performance' });
renderer.setPixelRatio(1);
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFShadowMap;
renderer.setClearColor(0x000000, 0);
document.getElementById('game').appendChild(renderer.domElement);
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(60, innerWidth / innerHeight, 0.25, 3200);
const t0 = performance.now();
const map = new CityMap();
const col = new CollisionWorld(map);
const city = new City(scene, map, col);
console.log('city build ms', (performance.now() - t0).toFixed(0));
const env = new Environment(renderer, scene);
env.setTime(parseFloat(q.get('t') || '9'));
env.timeScale = 0;
const post = new PostFX(renderer);
post.setSize(innerWidth, innerHeight);
const cx = parseFloat(q.get('x') || '-600'), cy = parseFloat(q.get('y') || '3'), cz = parseFloat(q.get('z') || '360');
const yaw = parseFloat(q.get('yaw') || '0'), pitch = parseFloat(q.get('pitch') || '0');
camera.position.set(cx, cy, cz);
camera.rotation.order = 'YXZ';
camera.rotation.set(pitch, yaw, 0);
let last = performance.now();
const sunScreen = new THREE.Vector2();
let frames = 0;
function frame() {
  const now = performance.now(); const dt = Math.min(0.05, (now - last) / 1000); last = now;
  env.update(dt, camera.position);
  env.sky.mesh.position.copy(camera.position);
  city.update(dt, camera.position, env.night);
  const sp = camera.position.clone().addScaledVector(env.sunDir, 1000).project(camera);
  sunScreen.set(sp.x * 0.5 + 0.5, sp.y * 0.5 + 0.5);
  const vis = sp.z < 1 ? env.sunVisible * Math.max(0, 1 - Math.hypot(sp.x, sp.y) / 1.6) : 0;
  post.composite.uniforms.uExposure.value = 1 + env.night * 0.9;
  post.render(scene, camera, sunScreen, vis * 0.5);
  frames++;
  requestAnimationFrame(frame);
}
frame();
window.__ready = true; window.__env = env; window.__scene = scene; window.__post = post; window.__r = renderer; window.__frames = () => frames;
